services:
  
  fastapi:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres


  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: raizes_do_nordeste
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  
      
volumes:
  pgdata:
