services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - payment
      - postgres
    volumes:
      - ./shared:/app/shared
    networks:
      - app-network

  payment:
    build:
      context: .
      dockerfile: payment/mock_pagamento/Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ./shared:/app/shared
    networks:
      - app-network

  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: raizes_do_nordeste
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: